deploy:
  artifact: build/libs/taskmaster-0.0.1-SNAPSHOT.jar
branch-defaults:
  bootjar:
    environment: taskmaster-dev
    group_suffix: null
global:
  application_name: taskmaster
  branch: null
  default_ec2_keyname: null
  default_platform: Java 8
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
