package com.goldbeardsea.taskmaster.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.ArrayList;
import java.util.UUID;

@DynamoDBTable(tableName = "AppUser")
public class AppUser {
    private UUID id;
    private String name;
    private ArrayList<Task> tasks;

    public AppUser() {}

    public AppUser(String name) {
        this.name = name;
        this.tasks = new ArrayList<>();
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public UUID getId() {
        return id;
    }

    @DynamoDBAttribute
    public void setId(UUID id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getName() {
        return name;
    }

    @DynamoDBAttribute
    public void setName(String name) {
        this.name = name;
    }

    @DynamoDBAttribute
    public ArrayList<Task> getTasks() {
        return tasks;
    }

    @DynamoDBAttribute
    public void setTasks(ArrayList<Task> tasks) {
        this.tasks = tasks;
    }
}
